{% set name = "pdbufr" %}
{% set version = "0.14.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5fd40f4dd07ef7b56f5d0c065debddb4afd45ddaa453addc731249ced8d31d13

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
    - setuptools >=61
    - setuptools-scm >=8
  run:
    - python >={{ python_min }}
    - attrs
    - pandas
    - pint
    - python-eccodes

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - pdbufr
  commands:
    - pip check

about:
  home: https://github.com/ecmwf/pdbufr
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Extracts data from a BUFR file as a Pandas DataFrame using ecCodes
  doc_url: https://pdbufr.readthedocs.io/en/latest/
  dev_url: https://github.com/ecmwf/pdbufr

extra:
  recipe-maintainers:
    - sandorkertesz
    - iainrussell
    - xylar
