{% set name = "pdbufr" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4a150b7d1dd1ee0ca8135cd9bccbbf3953d9bde5b1e7e2b85c2c8727c66c2186

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python >=3.7
    - pip
    - pytest-runner
  run:
    - python >=3.7
    - attrs
    - pandas
    - python-eccodes >=0.9.8

test:
  imports:
    - pdbufr

about:
  home: https://github.com/ecmwf/pdbufr
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Extracts data from a BUFR file as a Pandas DataFrame using ecCodes
  doc_url: https://pdbufr.readthedocs.io/en/latest/
  dev_url: https://github.com/ecmwf/pdbufr

extra:
  recipe-maintainers:
    - sandorkertesz
    - iainrussell
