{% set name = "pdbufr" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7f5f3fb4a78e41b8ad7d27d3be5230a7ead61008256b7b0a2e4cd22225a8d6ae

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python >=3.7
    - pip
    - pytest-runner
  run:
    - python >=3.7
    - attrs
    - pandas
    - python-eccodes >=0.9.8

test:
  imports:
    - pdbufr

about:
  home: https://github.com/ecmwf/pdbufr
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Extracts data from a BUFR file as a Pandas DataFrame using ecCodes
  doc_url: https://pdbufr.readthedocs.io/en/latest/
  dev_url: https://github.com/ecmwf/pdbufr

extra:
  recipe-maintainers:
    - sandorkertesz
    - iainrussell
