{% set name = "pdbufr" %}
{% set version = "0.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5127db40ac3a84850dafe547193ff02f845a8a7c58ed9e68476ef5f4675b7709

build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
  run:
    - python >={{ python_min }}
    - attrs
    - pandas
    - python-eccodes >=0.9.8

test:
  requires:
    - python {{ python_min }}
  imports:
    - pdbufr

about:
  home: https://github.com/ecmwf/pdbufr
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Extracts data from a BUFR file as a Pandas DataFrame using ecCodes
  doc_url: https://pdbufr.readthedocs.io/en/latest/
  dev_url: https://github.com/ecmwf/pdbufr

extra:
  recipe-maintainers:
    - sandorkertesz
    - iainrussell
